version: '3.8'
services:

  server:
    build: ./server
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    volumes:
      - logs:/project/logs
      - ./server:/project
      - /project/node_modules
    networks:
      - sern
    restart: always

  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/project/src
    stdin_open: true
    networks:
      - sern

  mysql:
    build: ./mysql
    volumes:
      - data:/data/db
    ports:
      - "3306:3306"
    networks:
      - sern

networks:
  sern:
    driver: bridge

volumes:
  data:
  logs: